version: "2.2"

services:
  geth:
    image: chapsuk/geth:prometheus
    container_name: dev_geth
    ports:
      - "10455:6060"
      # - "10545:8545"
    cpus: 0.3
    command: --http --syncmode "light" --http.addr="0.0.0.0" --http.vhosts="geth" --pprof --pprof.addr=0.0.0.0 --pprof.port=6060 --metrics

  grafana:
    image: grafana/grafana
    container_name: dev_geth_grafana
    ports:
      - "10007:3000"
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./grafana.db:/var/lib/grafana/grafana.db

  prometheus:
    image: prom/prometheus
    container_name: dev_geth_prometheus
    ports:
      - "10008:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
